syntax = "proto3";

package phoxal.component.bno085.v1;

message Vector3 {
  double x = 1;
  double y = 2;
  double z = 3;
}

message Quaternion {
  double w = 1;
  double x = 2;
  double y = 3;
  double z = 4;
}

message AccelerometerSample {
  Vector3 linear_acceleration_mps2 = 1;
}

message GyroscopeSample {
  Vector3 angular_velocity_radps = 1;
}

message ImuSample {
  optional Quaternion orientation = 1;
  Vector3 angular_velocity_radps = 2;
  Vector3 linear_acceleration_mps2 = 3;
  string sensor_frame_id = 4;
}
